version: 2
updates:
  - package-ecosystem: "docker-compose"
    directories:
      - "/dashboard/agent"
      - "/dashboard"
      - "/services/watchtower"
      - "/services/pi-hole"
      - "/services/pricebuddy"
      - "/services/github-backup"
      - "/services/portainer"
      - "/services/uptime-kuma"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "06:00"
      timezone: "Europe/Brussels"
